server {
    listen 80;
    client_max_body_size 100M;

    # OHIF Viewer
    location / {
        proxy_pass http://ohif:80/;
        proxy_set_header Host $host;
    }

    # Orthanc DICOMweb API (acessado pelo OHIF via browser)
    location /orthanc/ {
        proxy_pass http://orthanc:8042/;
        proxy_set_header Host $host;
        proxy_request_buffering off;
    }
}
